@startuml

' see: https://plantuml.com/ja-dark/activity-diagram-beta
'
' ## Rules
'
' 1. 不明なエラー発生時の Internal Error はアプリケーションロジックとは直接関係ない者であるため省略して記載
'     - 検査例外は必ず記載
'
' 2. DB 等の外部リソースへのアクセスは note で記述
'
'     note right
'         * output: File
'         * name: task.csv
'         * format: csv
'         ====
'         * 追加情報
'     end note
'
'     note right
'         * input: Database
'         * name: task
'         ====
'         * 追加情報
'     end note
'
' 3. 共通処理
'     - 次のフォーマットで記載
'         - #cyan:[procedure_name];
'     - `procedure_name` は、拡張子なしのファイル名

title タスク起票

start

#cyan:common_procedure_user_authorization;
:Task エンティティ新規作成;

if (入力エラー) then (yes)
  :BadRequest レスポンス;
  stop
else (no)
  :Task エンティティ保存;
  note right
    * Database
      * Task
    ====
    * DB への登録、ファイルへの出力は note で記述
    * メモが必要な場合は `====` で区切って下部に記載
  end note
endif

if (Task 重複エラー) then (yes)
  :BadRequest レスポンス;
else (no)
  :Task 起票成功レスポンス;
endif

stop

@enduml
