steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/realworld-api",
        "-f",
        "./server/cloudrun/Dockerfile",
        ".",
      ]
images:
  - "gcr.io/${PROJECT_ID}/realworld-api"
