version: "3.8"
services:
  db:
    image: postgres:15.3-bullseye
    environment:
      POSTGRES_PASSWORD: psql
      POSTGRES_USER: psql
      POSTGRES_DB: realworld
    ports:
      - 5432:5432
  migration:
    build: ./containers/migrations
    command: -path=/migrations/ -database postgres://psql:psql@db:5432/realworld?sslmode=disable up
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - ./realworld-api/resources/migrations:/migrations
  api:
    build: ./containers/dev/api
    volumes:
      - ./realworld-api:/app
      - ./.cache/docker/api/pkg:/go/pkg
    environment:
      DB_CONNECTION: postgres://psql:psql@db:5432/realworld?sslmode=disable
      WAIT_HOSTS: db:5432
    ports:
      - 8080:8080
  data_provision:
    build: ./containers/dev/testdata-loader
    volumes:
      - ./realworld-api:/app
      - ./.cache/docker/testdata-loader/pkg:/go/pkg
    environment:
      CONNECTION_NAME: postgres://psql:psql@db:5432/realworld?sslmode=disable
      WAIT_HOSTS: db:5432
