with-expecter: true
packages:
  github.com/ryutah/realworld-echo/realworld-api/usecase:
    config:
      dir: internal/mock/usecase
    interfaces:
      ErrorHandler:
      ErrorReporter:
      ErrorHandlerOption:
  github.com/ryutah/realworld-echo/realworld-api/domain/article/repository:
    config:
      dir: internal/mock/article/repository
      all: true
  github.com/ryutah/realworld-echo/realworld-api/domain/auth/service:
    config:
      dir: internal/mock/auth/service
      all: true
  github.com/ryutah/realworld-echo/realworld-api/domain/transaction:
    config:
      dir: internal/mock/transaction
      all: true
  github.com/ryutah/realworld-echo/realworld-api/infrastructure/psql/sqlc:
    config:
      dir: internal/mock/psql/sqlc
      all: true
  github.com/ryutah/realworld-echo/realworld-api/infrastructure/psql/sqlc/gen:
    config:
      dir: internal/mock/psql/sqlc/gen
      all: true
