// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/ryutah/realworld-echo/api/rest"
	"github.com/ryutah/realworld-echo/usecase"
)

// Injectors from wire.go:

func InitializeServer() *rest.Server {
	errorOutputPort := rest.NewErrorOutputPort()
	getArticleOutputPort := rest.NewGetArticleOutputPort(errorOutputPort)
	article := usecase.NewArticle(getArticleOutputPort)
	artcle := rest.NewArticle(article)
	server := rest.NewServer(artcle)
	return server
}

// wire.go:

var (
	restSet       = wire.NewSet(rest.NewServer, rest.NewArticle, usecaseSet)
	outputPortSet = wire.NewSet(rest.NewErrorOutputPort, rest.NewGetArticleOutputPort)
	usecaseSet    = wire.NewSet(usecase.NewArticle, wire.Bind(new(usecase.GetArticleInputPort), new(*usecase.Article)), outputPortSet)
)
